//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_App_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Emp
    {
        public int emp_id { get; set; }

        [DisplayName("Name")]
        public string emp_name { get; set; }

        [DisplayName("Gender")]
        public string gender { get; set; }

        [DisplayName("Is Fulltime")]
        public bool is_fulltime { get; set; }

        [DisplayName("Home/Street Address")]
        public string address { get; set; }

        [DisplayName("Country")]
        public string country { get; set; }

        [DisplayName("State")]
        public string state { get; set; }

        [DisplayName("City")]
        public string city { get; set; }

        [DisplayName("Image")]
        public string image_path { get; set; }

        public HttpPostedFileBase image { get; set; }
    }
}
